apiVersion: v1
kind: Secret
metadata:
  name: ansible-ssh-credentials
  namespace: liz-toolshed
type: Opaque
stringData:
  # EDIT: SSH user + password for the downstream worker node(s).
  # Used for both SSH login and (if needed) sudo become_password.
  username: "oleg"
  password: "password"
